### 예외처리

* 개발자가 처리할수 없는 오류(error)와 처리할 수 있는 예외(exception)의 두가지로 구분한다.
 
* 오류는 말 그대로 컨트롤할 수 없기 때문에 개발자는 예외만 처리하면 된다.
 
* 예외 발생 시 예외 메시지를 출력하고 프로그램을 강제로 종료시킨다.
 
* 이에 대응하여 예외 발생 시에도 프로그램을 종료시키지 않고 끝까지 동작하도록 처리하는 방법을 예외 처리라고 한다.
 
* java.lang.Throwable의 상속을 받는 Exception, Error 클래스가 있고, Exception 클래스로 예외를 처리한다.

### 컴파일 타임예외(Checked Exception) , 런타임예외(Unchecked Exception)

* 컴파일 타임 - 실행 전 환경

* 런타임 - 실행 후 환경

* 컴파일 예외(체크 예외)는 실행버튼을 누르기 전 IDE에서 알려주는 예외

* 런타임 예외(언체크 예외)는 실행버튼을 누른 후 실행 환경에서 알 수 있는 예외

* 컴파일 예외는 Exception, 런타임 예외는 RuntimeException 이 조상 클래스다.


#### trh-catch-finally

* try{}의 실행문을 실행하고 예외가 없을시 finally{}가 있으면 실행하고 종료
 
* try{}의 실행문에서 예외 발생시 해당 예외가 있는 catch(예외종류){}의 실행문을 실행하고 finally{}가 있으면 실행하고 종료
 
* catch()에 최상위 예외인 Exception을 정의한다면 모든 예외가 Exception으로 걸리게 된다.
 
* 예외 발생시 catch()문이 여러개 있다면 순서대로 거치기 때문에 최상위 예외인 Exception을 첫번째 catch() 에 정의한다면
 
* 무조건 모든 예외의 조상타입인 Exception으로 예외가 걸리기 때문에 두번째 이후의 catch()부터는 필요가 없어서 오류가 발생한다.
 
* 그래서 여러 하위 예외들을 거치다 최후에 만나도록 catch()의 마지막에 사용해야한다.
 

```
 public static void main(String[] args) {

        String msg = "";
        List<String> list = new ArrayList<>();

        try{ // 예외가 발생할 수도 있는 실행문 작성. 예외 발생시 해당 타입의 예외가 정의된 catch문으로 이동

            list.add("사자");
            list.add("호랑이");
            list.add("원숭이");
            list = Collections.unmodifiableList(list); // list를 수정할수 없게 만드는 메서드
            list.add("토끼");  // 위에서 수정할수 없게 했는데 추가해서 오류 발생
            msg = "처리가 완료되었습니다.";

        }catch (UnsupportedOperationException e){ // ()안에 예외 타입을 정의해 두고 해당 예외 발생시 처리

            // System.out.println(e.getMessage()); catch에서 발생한 오류 정보가 매개변수 e로 넘어와서 e.getMessage()로 오류 내용 출력
            msg = "처리 중에 오류가 발생했습니다.";

        }finally {  // 예외 여부와 관계없이 무조건 실행. finally{}는 옵션이라 추가하지 않아도 됨.

            System.out.println(msg);

        }

        //실행결과 - 처리 중에 오류가 발생했습니다.
    }
```

#### throw

* 강제로 예외를 발생시키는 방법
```
 public static void main(String[] args) {

        try{

            throw new UnsupportedOperationException("throw로 오류를 강제로 발생시켰습니다.");

        }catch (UnsupportedOperationException e){

            System.out.println(e.getMessage());

        }

        //실행결과 - throw로 오류를 강제로 발생시켰습니다.
    }
```

#### throws

* 예외 발생 시 현재 영역을 호출한 상위 영역에 예외를 위임하여 처리하게 한다.
 
* 최상위 메서드인 main()메서드에 throws 작성시 예외를 위임할 메서드가 없어 처리되지 않아 그대로 예외가 발생하게 된다.
 
* 이외에도 예외를 위임할 곳이 예외를 처리할 수 있는지 확인 후 사용해야 한다.

```
   public static void main(String[] args) {

        try {
            excute(); // excute()에서 위임한 예외를 받는다. 예외가 발생했으니 catch()에서 예외를 처리한다.
        } catch (Exception e) {
            System.out.println(e.getMessage() + "in Main method");
        }
    }

    public static void excute() throws Exception{ //예외 발생시 상위 영역으로 예외처리를 위임

        // 예외가 발생했지만 이곳에서 try-catch 문으로 처리하지 않고 이 메소드를 호출한 상위 영역으로 보낸다.
        throw new Exception("throws로 오류를 강제로 위임시켰습니다.");
    }

```

#### 사용자 지정 예외 클래스

* 기본 예외 클래스 이외에도 프로그래머가 직접 예외 클래스를 만들어 사용할 수 있다.
 
* 반드시 Exception 클래스로부터 상속받아야 한다.

```
 public static void main(String[] args) {
        
        List<String> list = Arrays.asList("인디안밥", "고래밥", "허니버터칩");
        try{
            hasBread(list); // 리스트에 "빵"이 포함되지 않았기 때문에 예외 발생
        }catch (BreadException e){
            System.out.println(e.getMessage());
        }
    }
    
    public static Boolean hasBread(List<String> list) throws BreadException{
        
        if(!list.contains("빵")){ // list에 "빵"이 포함되지 않았다면 만들어둔 사용자 지정 예외 발생 
            throw new BreadException();
        }
        return true;
    }


// 사용자 지정 예외클래스 생성
public class BreadException extends Exception{
    public BreadException(){
        super("빵이 포함되지 않는 치명적인 오류가 발생했습니다.");
    }
}
```

#### try-catch-resources

* 자바 7부터 추가된 기능이고 기존 try-catch을 보완했다.

```
// 기존 try-catch를 사용했을때
public static void main(String[] args) {

        AutoMachine machine = AutoMachine.getInstance();

        try {

            machine.run(); //run()메소드는 예외를 위임하기 때문에 try-catch로 작성해야 한다.

        } catch (Exception e) {

            System.out.println(e.getMessage());

        }finally {  //예외 발생여부에 상관없이 machine을 종료하려고 finally에 close를 작성했다.

            if(machine != null){

                try{

                    machine.close(); // 하지만 close()메서드도 예외를 위임하고 있기 때문에 try-catch에 작성해야 한다.
                                     // 예외 발생여부에 상관없이 종료하기 위해서 finally에 close를 작성했지만
                                     // close()도 예외를 위임하기 때문에 try-catch에 작성해야 하고, 그렇게 되면
                                     // 또다시 예외 발생여부에 따라 close()가 실행되지 않는 경우도 생긴다.
                                     // 결국 finally{}의 사용 목적을 이루지 못하게 된것이다.
                }catch (Exception e){

                    System.out.println(e.getMessage());

                }
            }
        }
    }

    // 실행결과
    // AutoMachine을 시작합니다.
    // AutoMachine이 동작합니다.
    // AutoMachine을 종료합니다.

// try-catch-resources를 사용했을때
public static void main(String[] args) {

        //try()내부에 Closeable를 구현한 인스턴스가 와야한다.
        try(AutoMachine machine = AutoMachine.getInstance()){ 

            machine.run(); //try 문이 끝나면 Closeable로 구현한 인스턴스의 close()메서드를 자동 호출한다.
                           // 즉 위의 코드와 달리 예외 여부와 상관없이 close()메소드가 반드시 실행된다.
                           // 그래서 finally에 close()를 사용할 필요가 없다.

        }catch (Exception e){

            System.out.println(e.getMessage());

        }finally { // close()는 try{}종료후 자동 실행되기 때문에 finally에 작성할 필요가 없다.

            System.out.println("모든 AutoMachine이 종료되었습니다.");

        }
    }

    // 실행결과
    // AutoMachine을 시작합니다.
    // AutoMachine이 동작합니다.
    // AutoMachine을 종료합니다.
    // 모든 AutoMachine이 종료되었습니다.

// AutoCloseable를 구현한 클래스 작성
public class AutoMachine implements AutoCloseable{

    private static AutoMachine machine;

    public static AutoMachine getInstance(){
        System.out.println("AutoMachine을 시작합니다.");
        machine = new AutoMachine();
        return machine;
    }

    public void run() throws Exception{
        System.out.println("AutoMachine이 동작합니다.");
    }

    @Override
    public void close() throws Exception {
        System.out.println("AutoMachine을 종료합니다.");
        machine = null;
    }
}

// AutoCloseable 인터페이스
public interface AutoCloseable {
    
    void close() throws Exception;
}
```

* try의 ()에 여러개의 인스턴스를 사용할 경우
```
// ;으로 인스턴스를 구분한다.
try(AutoMachine machine = AutoMachine.getInstance()
        ;AutoMachine2 machine2 = AutoMachine2.getInstance()){}

// 가독성 좋게 바꾼 방법
AutoMachine machine = AutoMachine.getInstance();
AutoMachine2 machine2 = AutoMachine2.getInstance();

try(machine; machine2){}
```
